//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorinWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class links
    {
        public int link_id { get; set; }
        public int resume_id { get; set; }
        public string name { get; set; }
        public string link { get; set; }
    
        public virtual resume resume { get; set; }
    }
}
