//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorinWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class technology_resume
    {
        public int technology_id { get; set; }
        public int resume_id { get; set; }
        public Nullable<bool> core_technology { get; set; }
        public Nullable<int> rank { get; set; }
    
        public virtual resume resume { get; set; }
        public virtual technology technology { get; set; }
    }
}
