//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorinWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class technology
    {
        public int technology_id { get; set; }
        public int competence_id { get; set; }
        public string name { get; set; }
        public int rank { get; set; }
        public Nullable<bool> core { get; set; }
    
        public virtual competence competence { get; set; }
    }
}
