//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorinWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workhistory
    {
        public int workhistory_id { get; set; }
        public int resume_id { get; set; }
        public string employer { get; set; }
        public string position { get; set; }
        public string description { get; set; }
        public string date { get; set; }
    
        public virtual resume resume { get; set; }
    }
}
